Repository aguirre-lab/ml4c3, pull requests merged in 2021-01, with the labels that each got.

#1247 Steps to remove sensitive data from repo
  CONTRIBUTING.md
Labels: documentation 📜

#1252 Lingering fixes to deidentify: update MRN map if new MRNs are remapped
  scripts/deidentify.py
  scripts/remove_duplicates_from_flowsheet.py
Labels: infrastructure 🚇

#1249 Adds argument to remove wrong formatted EDW files.
  ml4c3/arguments.py
  tensorize/edw/check_structure.py
Labels: infrastructure 🚇

#1253 Update pre-commit settings
  .pre-commit-config.yaml
  Makefile
Labels: infrastructure 🚇

#1262 scripts/deidentify.py saves MRNs and IDs to "mrn" and "id" column in CSV
  scripts/deidentify.py
Labels: bug 🐛, infrastructure 🚇

#1264 Fix case of "path" in tensorization
  ingest/icu/pre_tensorize_explorations.py
  ml4c3/recipes.py
  tensorize/bedmaster/readers.py
  tensorize/bedmaster/tensorizer.py
Labels: infrastructure 🚇

#1263 scripts/deidentify.py: user can set prefix for MRN map file name so the CSV file name does not become mgb-DATETIME1-DATETIME2.csv
  scripts/deidentify.py
Labels: infrastructure 🚇

#1254 Upload clustering example notebook
  notebooks/clustering/clustering_example.ipynb
Labels: documentation 📜

#1267 Make finder report regenerable with subset of signals
  clustering/entry.py
  clustering/objects/finder.py
  clustering/objects/structures.py
  ml4c3/arguments.py
  notebooks/clustering/clustering_example.ipynb
Labels: infrastructure 🚇

#1272 Fix bug tensorize without edw
  ingest/icu/tensorizer.py
  ml4c3/recipes.py
Labels: bug 🐛

#1277 Fix bug
  scripts/generate_hyperoptimize_json.py
  scripts/preprocess_bedmaster_alarms.py
  tensormap/icu_around_event.py
  tests/test_icu_tensor_maps.py
Labels: bug 🐛

#1281 c3po notebooks: change train/val/test ratio to 8:1:1 and remove percent sub cohort splits
  notebooks/c3po/c3po-preprocess-and-fix-bwh-mrns.ipynb
  notebooks/c3po/create-c3po-splits.ipynb
Labels: infrastructure 🚇

#1283 plot histogram in explore should only call np.histogram on non-nans
  ml4c3/plots.py
Labels: infrastructure 🚇

#1284 Fix typo in run script
  scripts/run.sh
Labels: bug 🐛
